name: Build and deploy Node.js app to Azure Web App - eclesiaworship

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Create dotenv file
        uses: iamsauravsharma/create-dotenv@v1.2.2
        env:
          PORT: 5000
          NODE_ENV: production
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          DROPBOX_CLIENT_ID: ${{ secrets.DROPBOX_CLIENT_ID }}
          DROPBOX_CLIENT_SECRET: ${{ secrets.DROPBOX_CLIENT_SECRET }}
          MONGO_URI: ${{ secrets.PROD_MONGO_URI }}

      - name: npm install and build
        run: |
          npm install
          npm run build
          zip -r eclesia-worship.zip . -x node_modules/\* package-lock.json

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: eclesia-worship
          path: |
            eclesia-worship.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: 'https://eclesiaworship.com'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: eclesia-worship
      - run: |
          unzip eclesia-worship.zip
          rm eclesia-worship.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - run: |
          az webapp config set --resource-group eclesiaworship_group --name eclesiaworship --startup-file "npm install && npm start"