name: ci-cd
run-name: ${{ github.actor }} built and tested the frontend
on: [push]
jobs:
  build-test:
    runs-on: ubuntu-latest
    # container: cypress/included:12.3.0
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: '16.16.0'
      - uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: '6.0.4'
      - uses: iamsauravsharma/create-dotenv@v1.2.2
        with:
          directory: server/
        env:
          PORT: 5000
          NODE_ENV: development
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          DROPBOX_CLIENT_ID: ${{ secrets.DROPBOX_CLIENT_ID }}
          DROPBOX_CLIENT_SECRET: ${{ secrets.DROPBOX_CLIENT_SECRET }}
          MONGO_URI: ${{ secrets.MONGO_URI }}

      - name: Start the server
        working-directory: ./server
        run: |
          npm ci &&
          npm start &
          cd ../client &&
          npm ci &&
          npm start &
          echo "Done!"
