name: Build and test the application

run-name: ${{ github.actor }} built and tested the frontend
on: [pull_request, workflow_dispatch]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: "6.0.4"
      - uses: iamsauravsharma/create-dotenv@v1.2.2
        env:
          PORT: 8080
          NODE_ENV: development
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          DROPBOX_CLIENT_ID: ${{ secrets.DROPBOX_CLIENT_ID }}
          DROPBOX_CLIENT_SECRET: ${{ secrets.DROPBOX_CLIENT_SECRET }}
          MONGO_URI: ${{ secrets.MONGO_URI }}

      - uses: cypress-io/github-action@v5
        with:
          start: npm run dev
          wait-on: "http://[::1]:4200"
          wait-on-timeout: 300

      - name: archive test artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            ./cypress/videos
            ./cypress/screenshots
