name: ci-cd
run-name: ${{ github.actor }} built and tested the frontend
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: '16'
      - name: Start the server
        working-directory: ./server
        run: |
          npm install
          npm run server
      - name: Start the frontend dev server
        working-directory: ../client
        run: |
          npm install
          npm start
      - name: Run e2e tests
        working-directory: ../client
        run: |
          npm run cy:open
